# Fly.io deployment configuration for SafeTrail
# Deploy with: fly deploy

app = "safetrail-backend"
primary_region = "ord"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  CORS_ORIGINS = "*"
  JWT_SECRET_KEY = "safetrail-jwt-secret-key-2024-change-in-production-fly"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "get"
    path = "/docs"
    port = 8000
    timeout = "5s"