# Railway.app deployment configuration for SafeTrail
# This file enables one-click deployment to Railway.app

# Build settings
[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

# Runtime settings  
[deploy]
startCommand = "python -m uvicorn demo_server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables
[env]
NODE_ENV = "production"
CORS_ORIGINS = "*"
JWT_SECRET_KEY = "safetrail-jwt-secret-key-2024-change-in-production-railway"

# Service settings
[settings]
generateDomain = true